apiVersion: v1
kind: Service
metadata: 
  name: bluegreen-demo-app
  labels: 
    name: bluegreen-demo-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: bluegreen-demo-app
    color: blue
  type: NodePort
